04.source/ideash/config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                  root GET    /                                                                                        top#index
#                          release_note GET    /release_note(.:format)                                                                  top#release_note
#                        account_signin GET    /account/signin(.:format)                                                                users/sessions#new
#                                       POST   /account/signin(.:format)                                                                users/sessions#create
#                        account_signup GET    /account/signup(.:format)                                                                users/registrations#new
#                                       POST   /account/signup(.:format)                                                                users/registrations#create
#                       account_signout GET    /account/signout(.:format)                                                               users/sessions#destroy
#                  account_profile_edit GET    /account/profile_edit(.:format)                                                          account#profile_edit
#                     user_confirmation GET    /user/confirmation(.:format)                                                             users/confirmations#show
#                                       POST   /user/confirmation(.:format)                                                             users/confirmations#create
#                          profile_edit GET    /account/edit(.:format)                                                                  users/registrations#profile_edit
#                        profile_update PATCH  /profile_update(.:format)                                                                users/registrations#profile_update
#                                  idea GET    /idea(.:format)                                                                          ideas#home
#                             idea_home GET    /idea/home(.:format)                                                                     ideas#home
#                          idea_history GET    /idea/history(.:format)                                                                  ideas#history
#                         idea_category GET    /idea/category(.:format)                                                                 ideas#category
#                         idea_memo_new GET    /idea/memo/new(.:format)                                                                 memo#new
#                                       POST   /idea/memo/new(.:format)                                                                 memo#new
#                             idea_memo POST   /idea/memo(.:format)                                                                     memo#create
#                                       GET    /idea/memo/edit/:id(.:format)                                                            memo#edit
#                                       PATCH  /idea/memo(.:format)                                                                     memo#update
#                idea_brainstorming_new GET    /idea/brainstorming/new(.:format)                                                        brainstorming#new
#             idea_brainstorming_replay GET    /idea/brainstorming/replay(.:format)                                                     brainstorming#replay
#             idea_brainstorming_create POST   /idea/brainstorming/create(.:format)                                                     brainstorming#create
#               idea_brainstorming_edit GET    /idea/brainstorming/edit/:id(.:format)                                                   brainstorming#edit
#                     jquery_test_index GET    /jquery_test/index(.:format)                                                             jquery_test#index
#                              ideachat GET    /ideachat(.:format)                                                                      ideachat#index
#                         ideachat_show GET    /ideachat/:id(.:format)                                                                  ideachat#show
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # INFO: トップページ
  root 'top#index'
  get 'release_note' => 'top#release_note', as: 'release_note'
  get 'top_category' => 'top#top_category', as: 'top_category'


  # INFO: devise(ユーザ認証関連)
  devise_for :users, skip: :all
  # devise_for :users
  devise_scope :user do
    get 'account/signin' => 'users/sessions#new'
    post 'account/signin' => 'users/sessions#create'
    get 'account/signup' => 'users/registrations#new'
    post 'account/signup' => 'users/registrations#create'
    get 'account/signout' => 'users/sessions#destroy'
    get 'account/profile_edit' => 'users/edit'
    # get 'user/confirmation/new' => 'users/confirmations#new'
    get 'user/confirmation' => 'users/confirmations#show'
    post 'user/confirmation' => 'users/confirmations#create'
    # INFO: アカウント設定
    # get 'account/edit' => 'users/registrations#edit'
    get 'account/edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'account/edit', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  # INFO: ユーザのホーム画面
  get 'idea/home' => 'ideas#home'
  get 'idea/history' => 'ideas#history'
  get 'idea/category' => 'ideas#category'
  # get 'idea/account' => 'ideas#account'

  # INFO: メモ
  get 'idea/memo/new' => 'memo#new'
  post 'idea/memo/new' => 'memo#new'
  post 'idea/memo' => 'memo#create'
  # get 'idea/memo/show' => 'memo#show'
  get 'idea/memo/edit/:id' => 'memo#edit'
  patch '/idea/memo' => 'memo#update'

  # INFO: ブレインストーミング
  get 'idea/brainstorming/new' => 'brainstorming#new'
  get 'idea/brainstorming/replay' => 'brainstorming#replay'
  post 'idea/brainstorming/create' => 'brainstorming#create'
  get 'idea/brainstorming/edit/:id' => 'brainstorming#edit', as: :idea_brainstorming_edit

  # INFO: マンダラート
  get'idea/mandarat/new' => 'mandarat#new'

04.source/ideash/app/controllers/top_controller.rb
class TopController < ApplicationController
  require 'csv'
  skip_before_action :authenticate_user!

  def index
    @release_note = read_release_note_csv
  end

  def release_note
    @release_note = read_release_note_csv
  end

  private

  def read_release_note_csv
    CSV.read("app/assets/csv/release_note.csv", headers: true, return_headers: false)
  end
end

04.source/ideash/app/helpers/top_helper.rb
module TopHelper
end

04.source/ideash/app/views/top/index.html.erb
<% content_for(:html_title) { 'top | Ideash' } %>
<!-- 背景緑部分 -->
<div class="top" id="top_img">
  <div class="seg_1">
    <div class="background_text no_select" id="home">
      <title>Ideash アイデア発想ツール</title>
      Inspiration<br>
      w /<br>
      Ideash<br>
    </div>
    <%= image_tag 'thinkman.webp', class: 'image_think_man no_select' %>
    <div class="btns_1">
      <div class="ui massive buttons btns_1_1">
        <%= link_to "Sign In", :account_signin, class: "ui inverted button" %>
        <div class="or"></div>
        <%= link_to "Sign Up", :account_signup, class: "ui black button" %>
      </div>
      <div class="ui styled accordion release_note_accordion">
        <div class="title accordion">
          <i class="dropdown icon"></i>
          リリースノート
        </div>
        <div class="content">
          <div class="ui list">
            <% @release_note.each do |row| %>
              <div class="item">
                <i class="angle right icon"></i>
                <div class="release_note_content">
                  <%= link_to row['description'].split("//")[0], release_note_path, class: 'header' %>
                  <div class="description"><%= row['date'] %></div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="seg_2">
    <div class="background_text no_select" id="concept">
      our Life is<br>
      Creative.<br>
      Creativity<br>
      fr Simple.<br>
      <%= image_tag 'icon_index.svg', class: 'icon_1 no_select' %>
    </div>
  </div>
</div>

<div class="gradation"></div>

<!-- 背景白部分 -->
<div class="about">

  <div class="seg_3"><!--　隙間　-->
  </div>

  <div class="seg_h1">
    <!--50文字以内-->
    <h1>アイデア出しが苦手な人に是非使ってもらいたいアプリ<br>ネット環境があれば使えるオンラインアイデア発想ツール</h1>
  </div>
  <div class="seg_4" id="about">
    <div class="headers">
      <h2>初めてでも、近くにいなくても</h2>
      <h3>Ideashは発想を容易にするツールです</h3>
    </div>
    <p>PCさえあれば簡単に発想手法を試すことができます。<br>
      専用の用紙やホワイトボードなど面倒な準備は一切必要ありません。シンプルな画面に従って作業を行うだけでクリエイティブな人生を送れるようになります。</p>
    <%= image_tag 'top_sample_1.webp', class: 'sample_1 no_select' %>
  </div>

  <div class="seg_5">
    <div class="headers">
      <h2>選ぶ、集まる、思いつく</h2>
      <h3>様々な場面での利用を想定</h3>
    </div>
    <p>Ideashの利用手順は<br>
      １　発想手法を選ぶ<br>
      ２　参加者を集める(リンクを渡すだけで参加できます)<br>
      ３　ツールの指示に従う<br>
      たったこれだけです。多様なテーマや参加人数に対応できるよう発想手法も複数用意されています。<br>
      さらに、アップデートを行い更に使いやすいツールへと進化していきます。</p>
    <%= image_tag 'top_sample_2.webp', class: 'sample_2 no_select' %>
    <br>
    <div class="function_show_btn">
      <%= link_to "使える機能を見てみる", top_category_path, class: "ui grey button" %>
    </div>
  </div>

  <div class="seg_6 ui center aligned">
    <h2>さあ、まずはサインアップしましょう</h2>
    <h2>Inspiration with Ideash</h2>
    <%= image_tag 'icon.svg', class: 'icon no_select' %>
    <div class="btn_2">
      <div class="ui huge buttons btns_2_1">
        <%= link_to "Sign In", :account_signin, class: "ui teal button" %>
        <div class="or"></div>
        <%= link_to "Sign Up", :account_signup, class: "ui black button" %>
      </div>
    </div>
  </div>
</div>

<div class="footer">
  <%= image_tag 'thinkman.webp', class: 'man no_select' %>
  <ul class="footer-menu">
    <a href="#home">
      <li>home　｜　</li>
    </a>
    <a href="#concept">
      <li>concept 　｜　</li>
    </a>
    <a href="#about">
      <li>about</li>
    </a>
  </ul>
</div>

04.source/ideash/app/views/top/release_note.html.erb
<div class="release_note_segment">
  <table class="ui teal table release_note_table">
    <thead>
    <tr>
      <th>Version</th>
      <th>更新日付</th>
      <th>更新内容</th>
      <th>追加機能</th>
    </tr>
    </thead>
    <tbody>
    <% @release_note.each do |row| %>
      <tr>
        <td><%= row["version"] %></td>
        <td><%= row["date"] %></td>
        <td>
          <% for description in row["description"].split("//") do %>
            <%= description %><br>
          <% end %>
        </td>
        <td>
          <% for function in row["function"].split("//") do %>
            <%= function %><br>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

04.source/ideash/app/views/top/top_category.html.erb
<div class="category_segment">
  <h1 class="header">機能一覧</h1>
  <ul class="horizontal-list categories">
    <li class="horizontal-item category">
      <div class="techname_eng">Memo</div>
      <div class="techname_ja">メモ</div>
      <div><i class="edit huge icon techname_icon"></i></div>
      <div class="recommend_num">
        推奨人数：１人
      </div>
      <br>
      <i class="question circle outline icon js-modal-open" id="memo-more-info"></i>もっと詳しく
      <div class="explain">
        考えていることを書き連ねる<br>ことで、考えを整理し発想を<br>しやすくする技法
      </div>
      <hr>
      <div class="recommend_point">
        真っ白なフィールドを思考で<br>埋めていくことで新しい発想<br>が可能
      </div>
    </li>
    <li class="horizontal-item category">
      <div class="techname_eng">Brainstorming</div>
      <div class="techname_ja">ブレインストーミング</div>
      <div><i class="tags huge icon techname_icon"></i></div>
      <div class="recommend_num">
        推奨人数：２人〜
      </div>
      <br>
      <i class="question circle outline icon js-modal-open" id="brainstorming-more-info"></i>もっと詳しく
      <div class="explain">
        集団でアイデアを出し合うこ<br>とによって相互交錯の連鎖反<br>応や発想の誘発を期待する技法
      </div>
      <hr>
      <div class="recommend_point">
        アイデアを出し合い、融合さ<br>せることで、斬新で質な発想<br>が可能<br>
      </div>
    </li>
    <li class="horizontal-item category">
      <div class="techname_eng">Mandarat</div>
      <div class="techname_ja">マンダラート</div>
      <div><i class="expand arrows alternate huge icon techname_icon"></i></div>
      <div class="recommend_num">
        推奨人数：１人〜
      </div>
      <br>
      <i class="question circle outline icon js-modal-open" id="mandarat-more-info"></i>もっと詳しく
      <div class="explain">
        ９×９のマス目に連想される<br>語句、または関連語句を記述<br>しアイデアのタネを育てる技法
      </div>
      <hr>
      <div class="recommend_point">
        アイデアの整理や拡大が図れ<br>効果的なアイデアを発掘する<br>ことが可能
      </div>
    </li>
    <li class="horizontal-item category">
      <div class="techname_eng">Word GACHA</div>
      <div class="techname_ja">単語ガチャ</div>
      <div><i class="chart pie huge icon techname_icon"></i></div>
      <div class="recommend_num">
        推奨人数：１人
      </div>
      <br>
      <i class="question circle outline icon js-modal-open" id="word-gacha-more-info"></i>もっと詳しく
      <div class="explain">
        訳750個の単語が出てくる<br>10連ガチャ<br>語彙ランクでレアリティが変化
      </div>
      <hr>
      <div class="recommend_point">
        ランダムに表示される単語か<br>ら発送の手助けに<br><br>
      </div>
    </li>
    <li class="horizontal-item category">
      <div class="techname_eng">Word SLOT</div>
      <div class="techname_ja">単語スロット</div>
      <div><i class="chess king huge icon techname_icon"></i></div>
      <div class="recommend_num">
        推奨人数：１人
      </div>
      <br>
      <i class="question circle outline icon js-modal-open" id="word-slot-more-info"></i>もっと詳しく
      <div class="explain">
        <br>約750個の単語が出てくる<br>スロット<br>
      </div>
      <hr>
      <div class="recommend_point">
        単語の組み合わせから自由な<br>発想へ繋がる<br><br>
      </div>
    </li>
  </ul>
  <div class="back_btn">
    <%= link_to "戻る", root_path, class: "ui grey button" %>
  </div>
  <div class="modal js-modal" id="memo-modal-window">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <%= image_tag 'memo_info_img', class: 'image_info_memo' %>
      <ul>
        <li class="info-text">①メモのタイトルを入力してください。</li>
        <li class="info-text">②メモの内容を入力してください。</li>
        <li class="info-text">③入力が終わったら「保存」ボタンをクリック！</li>
        <li class="info-text">保存されたメモは、右のリストから<br>確認・編集することができます。</li>
      </ul>
      <a class="js-modal-close" href="">閉じる</a>
    </div>
  </div>
  <div class="modal js-modal" id="brainstorming-modal-window">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <%= image_tag 'brainstorming_info_img1', class: 'image1_info_brainstorming' %>
      <%= image_tag 'brainstorming_info_img2', class: 'image2_info_brainstorming' %>
      <ul>
        <li class="info-text">①作成時に入力したテーマが表示されます。</li>
        <li class="info-text">②思いついた案を入力してEnterで送信。</li>
        <li class="info-text">③全ての参加者の案が表示されます。</li>
        <li class="info-text">④残り時間・参加者の確認やチャットが行えます。</li>
        <li class="info-text">⑤グループを追加することができます。</li>
        <li class="info-text">⑥グループ名を変更することができます。</li>
        <li class="info-text">⑦ドラッグ&ドロップで案をグルーピングできます。</li>
      </ul>
      <a class="js-modal-close" href="">閉じる</a>
    </div>
  </div>
  <div class="modal js-modal" id="mandarat-modal-window">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <%= image_tag 'mandarat_info_img1', class: 'image1_info_mandarat' %>
      <%= image_tag 'mandarat_info_img2', class: 'image2_info_mandarat' %>
      <ul>
        <li class="info-text">①メイン・サブテーマが表示されます。</li>
        <li class="info-text">②入力してマスを埋めていきます。<br>他の参加者が編集していると色が変わります。</li>
        <li class="info-text">③矢印の方向に移動します。上下左も同様。</li>
        <li class="info-text">④全体画面（画像２枚目）を見ることができます。</li>
        <li class="info-text">⑤現在開いている場所が表示されます。<br>選択することで移動することもできます。</li>
        <li class="info-text">⑥メインテーマとサブテーマが表示されます。</li>
        <li class="info-text">⑦残り時間・参加者の確認やチャットが行えます。</li>
        <li class="info-text">⑧81マス全てが表示されます。（閲覧のみ）<br>画面をクリックすることで元の画面に戻れます。</li>
      </ul>
      <a class="js-modal-close" href="">閉じる</a>
    </div>
  </div>
  <div class="modal js-modal" id="word-gacha-model-window">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <%= image_tag 'gacha_info_img1', class: 'image1_info_gacha' %>
      <%= image_tag 'gacha_info_img2', class: 'image2_info_gacha' %>
      <ul>
        <li class="info-text">①「回す」を押すと結果画面（画像右）に移動します。</li>
        <li class="info-text">②初期画面（画像左）に移動します。</li>
        <li class="info-text">③ランダムに選ばれた10個のワードが表示されます。</li>
      </ul>
      <a class="js-modal-close" href="">閉じる</a>
    </div>
  </div>
  <div class="modal js-modal" id="word-slot-model-window">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <%= image_tag 'slot_info_img', class: 'image_info_slot' %>
      <ul>
        <li class="info-text">①「回す」を押すとスロットが始まります。</li>
        <li class="info-text">②スロットを止めることができます。</li>
        <li class="info-text">③ランダムに選ばれたワードが表示されます。</li>
      </ul>
      <a class="js-modal-close" href="">閉じる</a>
    </div>
  </div>
</div>