04.source/ideash/config/routes.rb
#                                       POST   /account/signup(.:format)                                                                users/registrations#create
#                       account_signout GET    /account/signout(.:format)                                                               users/sessions#destroy
#                  account_profile_edit GET    /account/profile_edit(.:format)                                                          account#profile_edit
#                     user_confirmation GET    /user/confirmation(.:format)                                                             users/confirmations#show
#                                       POST   /user/confirmation(.:format)                                                             users/confirmations#create
#                          profile_edit GET    /account/edit(.:format)                                                                  users/registrations#profile_edit
#                        profile_update PATCH  /profile_update(.:format)                                                                users/registrations#profile_update
#                                  idea GET    /idea(.:format)                                                                          ideas#home
#                             idea_home GET    /idea/home(.:format)                                                                     ideas#home
#                          idea_history GET    /idea/history(.:format)                                                                  ideas#history
#                         idea_category GET    /idea/category(.:format)                                                                 ideas#category
#                         idea_memo_new GET    /idea/memo/new(.:format)                                                                 memo#new
#                                       POST   /idea/memo/new(.:format)                                                                 memo#new
#                             idea_memo POST   /idea/memo(.:format)                                                                     memo#create
#                                       GET    /idea/memo/edit/:id(.:format)                                                            memo#edit
#                                       PATCH  /idea/memo(.:format)                                                                     memo#update
#                idea_brainstorming_new GET    /idea/brainstorming/new(.:format)                                                        brainstorming#new
#             idea_brainstorming_replay GET    /idea/brainstorming/replay(.:format)                                                     brainstorming#replay
#             idea_brainstorming_create POST   /idea/brainstorming/create(.:format)                                                     brainstorming#create
#               idea_brainstorming_edit GET    /idea/brainstorming/edit/:id(.:format)                                                   brainstorming#edit
#                     jquery_test_index GET    /jquery_test/index(.:format)                                                             jquery_test#index
#                              ideachat GET    /ideachat(.:format)                                                                      ideachat#index
#                         ideachat_show GET    /ideachat/:id(.:format)                                                                  ideachat#show
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # INFO: トップページ
  root 'top#index'
  get 'release_note' => 'top#release_note', as: 'release_note'
  get 'top_category' => 'top#top_category', as: 'top_category'


  # INFO: devise(ユーザ認証関連)
  devise_for :users, skip: :all
  # devise_for :users
  devise_scope :user do
    get 'account/signin' => 'users/sessions#new'
    post 'account/signin' => 'users/sessions#create'
    get 'account/signup' => 'users/registrations#new'
    post 'account/signup' => 'users/registrations#create'
    get 'account/signout' => 'users/sessions#destroy'
    get 'account/profile_edit' => 'users/edit'
    # get 'user/confirmation/new' => 'users/confirmations#new'
    get 'user/confirmation' => 'users/confirmations#show'
    post 'user/confirmation' => 'users/confirmations#create'
    # INFO: アカウント設定
    # get 'account/edit' => 'users/registrations#edit'
    get 'account/edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'account/edit', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  # INFO: ユーザのホーム画面
  get 'idea/home' => 'ideas#home'
  get 'idea/history' => 'ideas#history'
  get 'idea/category' => 'ideas#category'
  # get 'idea/account' => 'ideas#account'

  # INFO: メモ
  get 'idea/memo/new' => 'memo#new'
  post 'idea/memo/new' => 'memo#new'
  post 'idea/memo' => 'memo#create'
  # get 'idea/memo/show' => 'memo#show'
  get 'idea/memo/edit/:id' => 'memo#edit'
  patch '/idea/memo' => 'memo#update'

  # INFO: ブレインストーミング
  get 'idea/brainstorming/new' => 'brainstorming#new'
  get 'idea/brainstorming/replay' => 'brainstorming#replay'
  post 'idea/brainstorming/create' => 'brainstorming#create'
  get 'idea/brainstorming/edit/:id' => 'brainstorming#edit', as: :idea_brainstorming_edit

  # INFO: マンダラート
  get'idea/mandarat/new' => 'mandarat#new'
  get 'idea/mandarat/replay' => 'mandarat#replay'
  post 'idea/mandarat/create' => 'mandarat#create'
  get 'idea/mandarat/edit/:id' => 'mandarat#edit', as: :idea_mandarat_edit
  get 'idea/mandarat/_process_1' => 'mandarat#_process_1'

  # INFO: 単語ガチャ
  get 'idea/word_gacha/edit' => 'word_gacha#edit', as: :idea_word_gacha_edit
  get 'idea/word_gacha/get_wordgacha_jsons' => 'api#get_wordgacha_jsons', as: 'wordgacha_jsons'

  # INFO: 単語スロット
  get 'idea/word_slot/edit' => 'word_slot#edit', as: :idea_word_slot_edit
  get 'idea/word_slot/get_wordslot_jsons' => 'api#get_wordgacha_jsons', as: 'wordslot_jsons'


  # NOTE: Action Cable の有効化
  mount ActionCable.server => '/cable'
  # developmentモードでのみ以下のルーティングが行われる
  if Rails.env.development?
    # NOTE: jQueryのテスト用
    get 'jquery_test/index'
    # NOTE: WebSocketのテスト用チャット画面
    get 'ideachat/' => 'ideachat#index'
    get 'ideachat/:id' => 'ideachat#show', as: :ideachat_show
  end

04.source/ideash/app/controllers/mandarat_controller.rb
class MandaratController < ApplicationController
  layout 'head_left_layout'

  def replay
    check_idea_category
  end

  def edit
    check_idea_category
    @idea = Idea.find_by(id: params[:id])
    @idea_logs = @idea.idea_logs
    @idea_users = @idea.user
    # 既に登録されているかどうか
    is_added_user = @idea_users.where(id: current_user.id).exists?
    unless is_added_user
      #TODO: 公開状態でない場合はアクセスしてきたユーザを蹴る(公開状態の実装後)
      # redirect_to idea_home_path
      user = User.find_by(id: current_user.id)
      user_idea = user.user_idea.new do |idea|
        idea.user_id = user.id
        idea.idea_id = @idea.id
      end
      p user_idea.save
    end
  end

  def create
    user = User.find_by(id: current_user.id)
    new_idea = user.idea.new do |idea|
      idea.idea_category_id = Settings.idea_category_id.mandarat
      idea.idea_name = params[:theme]
    end

    if new_idea.save!
      if !params[:is_unlimited]
        IdeaLog.create! idea_id: new_idea.id, query: {'user_id': current_user.id, 'mode': 'system', 'system': {'operation': 'process1', 'option': '0'}}
      else
        if Rails.env.development?
          # テスト用(秒単位)
          IdeaLog.create! idea_id: new_idea.id, query: {'user_id': current_user.id, 'mode': 'system', 'system': {'operation': 'process1', 'option': (params[:process1].to_i).to_s}}
        else
          # 本番用(分単位)
          IdeaLog.create! idea_id: new_idea.id, query: {'user_id': current_user.id, 'mode': 'system', 'system': {'operation': 'process1', 'option': (params[:process1].to_i * 60).to_s}}
        end
      end

      logger.debug "create new idea: #{new_idea.inspect}"
      redirect_to idea_mandarat_edit_url(id: new_idea.id)
    else
    end
  end
end

04.source/ideash/app/views/mandarat/_process_1.html.erb
<%# マンダラート　全体表示画面 %>
<div class="edit_body" id="edit_body">
  <div class="mandarat-overview" id="zoomview">
    <table>
      <tr>
        <td class="main-theme-block">
          <div class="sub-theme-block" id="sub-theme-block-1">
            <table border="1" class="tab">
              <tr><td><div id="0"></div></td><td><div id="1"></div></td><td><div id="2"></div></td></tr>
              <tr><td><div id="3"></div></td><td><div id="4"></div></td><td><div id="5"></div></td></tr>
              <tr><td><div id="6"></div></td><td><div id="7"></div></td><td><div id="8"></div></td></tr>
            </table>
          </div>
        </td>
        <td class="main-theme-block">
          <div class="sub-theme-block" id="sub-theme-block-2">
            <table border="1" class="tab">
              <tr><td><div id="10"></div></td><td><div id="11"></div></td><td><div id="12"></div></td></tr>
              <tr><td><div id="13"></div></td><td><div id="14"></div></td><td><div id="15"></div></td></tr>
              <tr><td><div id="16"></div></td><td><div id="17"></div></td><td><div id="18"></div></td></tr>
            </table>
          </div>
        </td>
        <td class="main-theme-block">
          <div class="sub-theme-block" id="sub-theme-block-3">
            <table border="1" class="tab">
              <tr><td><div id="20"></div></td><td><div id="21"></div></td><td><div id="22"></div></td></tr>
              <tr><td><div id="23"></div></td><td><div id="24"></div></td><td><div id="25"></div></td></tr>
              <tr><td><div id="26"></div></td><td><div id="27"></div></td><td><div id="28"></div></td></tr>
            </table>
          </div>
        </td>
      </tr>
      <tr>
        <td class="main-theme-block">
          <div class="sub-theme-block" id="sub-theme-block-4">
            <table border="1" class="tab">
              <tr><td><div id="30"></div></td><td><div id="31"></div></td><td><div id="32"></div></td></tr>
              <tr><td><div id="33"></div></td><td><div id="34"></div></td><td><div id="35"></div></td></tr>
              <tr><td><div id="36"></div></td><td><div id="37"></div></td><td><div id="38"></div></td></tr>
            </table>
          </div>
        </td>
        <td class="main-theme-block">
          <div class="sub-theme-block" id="sub-theme-block-5">
            <table border="1" class="tab">
              <tr><td><div id="40"></div></td><td><div id="41"></div></td><td><div id="42"></div></td></tr>
              <tr><td><div id="43"></div></td><td><div id="44"></div></td><td><div id="45"></div></td></tr>
              <tr><td><div id="46"></div></td><td><div id="47"></div></td><td><div id="48"></div></td></tr>
            </table>
          </div>
        </td>
        <td class="main-theme-block">
          <div class="sub-theme-block" id="sub-theme-block-6">
            <table border="1" class="tab">
              <tr><td><div id="50"></div></td><td><div id="51"></div></td><td><div id="52"></div></td></tr>
              <tr><td><div id="53"></div></td><td><div id="54"></div></td><td><div id="55"></div></td></tr>
              <tr><td><div id="56"></div></td><td><div id="57"></div></td><td><div id="58"></div></td></tr>
            </table>
          </div>
        </td>
      </tr>
      <tr>
        <td class="main-theme-block">
          <div class="sub-theme-block" id="sub-theme-block-7">
            <table border="1" class="tab">
              <tr><td><div id="60"></div></td><td><div id="61"></div></td><td><div id="62"></div></td></tr>
              <tr><td><div id="63"></div></td><td><div id="64"></div></td><td><div id="65"></div></td></tr>
              <tr><td><div id="66"></div></td><td><div id="67"></div></td><td><div id="68"></div></td></tr>
            </table>
          </div>
        </td>
        <td class="main-theme-block">
          <div class="sub-theme-block" id="sub-theme-block-8">
            <table border="1" class="tab">
              <tr><td><div id="70"></div></td><td><div id="71"></div></td><td><div id="72"></div></td></tr>
              <tr><td><div id="73"></div></td><td><div id="74"></div></td><td><div id="75"></div></td></tr>
              <tr><td><div id="76"></div></td><td><div id="77"></div></td><td><div id="78"></div></td></tr>
            </table>
          </div>
        </td>
        <td class="main-theme-block">
          <div class="sub-theme-block" id="sub-theme-block-9">
            <table border="1" class="tab">
              <tr><td><div id="80"></div></td><td><div id="81"></div></td><td><div id="82"></div></td></tr>
              <tr><td><div id="83"></div></td><td><div id="84"></div></td><td><div id="85"></div></td></tr>
              <tr><td><div id="86"></div></td><td><div id="87"></div></td><td><div id="88"></div></td></tr>
            </table>
          </div>
        </td>
      </tr>
    </table>
  </div>
</div>

04.source/ideash/app/views/mandarat/_process_2.html.erb
<%# マンダラート　メイン編集画面 %>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
</head>
<div class="edit_body" id="edit_body">
  <%= render :partial => 'mandarat/shared' %>
  <div class="mandarat-main">
    <div class="to-up-area">
      <div id="to-up-button"><i class="caret down vertically flipped huge link icon"></i></div>
    </div>
    <div class="to-left-area">
      <div id="to-left-button"><i class="caret down clockwise rotated huge link icon"></i></div>
    </div>
    <div class="mandarat-blocks" id="zoom">
      <table border="1">
        <!--
        あとで書き換える
        縦に伸びてくから文字数制限つけて欲しい
        -->
        <tr>
          <td>
            <div class="text_block" id="zoom_div_0"></div>
            <textarea class="t0" id="zoom_0"></textarea>
          </td>
          <td>
            <div class="text_block" id="zoom_div_1"></div>
            <textarea class="t1" id="zoom_1"></textarea>
          </td>
          <td>
            <div class="text_block" id="zoom_div_2"></div>
            <textarea class="t2" id="zoom_2"></textarea>
          </td>
        </tr>
        <tr>
          <td>
            <div class="text_block" id="zoom_div_3"></div>
            <textarea class="t3" id="zoom_3"></textarea>
          </td>
          <td>
            <div class="text_block" id="zoom_div_4"></div>
            <textarea class="t4" id="zoom_4"></textarea>
          </td>
          <td>
            <div class="text_block" id="zoom_div_5"></div>
            <textarea class="t5" id="zoom_5"></textarea>
          </td>
        </tr>
        <tr>
          <td>
            <div class="text_block" id="zoom_div_6"></div>
            <textarea class="t6" id="zoom_6"></textarea>
          </td>
          <td>
            <div class="text_block" id="zoom_div_7"></div>
            <textarea class="t7" id="zoom_7"></textarea>
          </td>
          <td>
            <div class="text_block" id="zoom_div_8"></div>
            <textarea class="t8" id="zoom_8"></textarea>
          </td>
        </tr>
      </table>
    </div>

    <!--hiddenで無理やり-->
    <dev hidden>
      <% result = Hash.new %>
      <% for i in 0..8 do %>
        <% for j in 0..8 do %>
          <% result.store(i * 10 + j, "") %>
        <% end %>
      <% end %>
      <% result.store(44,idea.idea_name) %>
      <input type="hidden" id="44_main_theme" value=<%= idea.idea_name %>>
      <% for content in idea_logs do %>
        <% if content.query['mode'] == 'edit' %>
          <%= result[content.query["edit"]["object_id"]] = content.query["edit"]["content"] %>
        <% end %>
      <% end %>
      <% for i in 0..8 do %>
        <% for j in 0..8 do %>
          <input type="hidden" name="read_<%= i * 10 + j %>" value="<%= result[i * 10 + j] %>">
        <% end %>
      <% end %>
    </dev>

    <div class="to-right-area">
      <div id="to-right-button"><i class="caret down counterclockwise rotated huge link icon"></i></div>
    </div>
    <div class="to-down-area">
      <div id="to-down-button"><i class="caret down huge link icon"></i></div>
    </div>
  </div>
</div>

04.source/ideash/app/views/mandarat/_shared.erb
<div class="mandarat-shared">
  <div class="current-location-area" id="radio-btn">
    <div class="ui header" id="to_while_link">
      <a id="allview"><i class="compress arrows alternate icon"></i>全体を見る</a>
    </div>
    <table border="1">
      <% 3.times do |i| %>
        <tr>
          <% 3.times do |j| %>
            <td data-minimap="true" data-minimap-id=<%= (i * 3 + j) * 10 %>>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="themes-area">
    <div class="ui link list">
      <div class="active item">メインテーマ</div>
      <div class="item" id="main-theme"><p id="main"></p></div>
      <br>
      <div class="active item">サブテーマ</div>
      <table border="1" class="theme-tab">
        <% for i in 1..8 %>
          <tr>
            <td>
              <% if i < 5 then %>
                <div class="item" id="sub-theme-<%= i %>"><p class="themes" id="theme<%= i - 1 %>"></p></div>
              <% else %>
                <div class="item" id="sub-theme-<%= i %>"><p class="themes" id="theme<%= i %>"></p></div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

</div>

04.source/ideash/app/views/mandarat/edit.html.erb
<span class="websocket-mandarat" id="idea_logs" data-idea_id="<%= @idea.id %>"></span>

<div id="process_2"><%= render :partial => 'mandarat/process_2', locals: {idea: @idea, idea_logs: @idea_logs} %></div>
<div id="process_1"><%= render :partial => 'mandarat/process_1', locals: {idea: @idea, idea_logs: @idea_logs} %></div>

<%= content_for :right_menu do %>
  <%= render :partial => 'shared/right_menu', locals: {users: @idea_users} %>
<% end %>

04.source/ideash/app/views/mandarat/new.html.erb
<div class="tech_about_body">
  <div class="ui segments block-tech-about">
    <div class="ui segment">
      <div class="techname">マンダラート</div>
    </div>
    <div class="ui segment">
      <%= form_with url: idea_mandarat_create_path, model: @user_idea, local: true do |f| %>
        <h4 class="header-text process">手順</h4>
        <ul>
          <li>手順①：3*3のマスの中心にテーマを置き、関連語句や連想されるものを周りに記述していく</li>
          <li>手順②：①で出た語句をサブテーマとして中心に置き、①と同じ手順を繰り返す</li>
          <li>手順③：出てきた語句からアイデアへと繋がりそうなものを拾い上げていく</li>
        </ul>
        <h4 class="header-text rule">ルール</h4>
        <ul>
          <li>批判禁止　出たアイデアを批判したり、実現性を求めたりしないこと。</li>
          <li>自由奔放　柔軟なアイデアを出すために固定概念や慣習に囚われないようにする。</li>
        </ul>
        <h4 class="header-text timer-setting">時間設定(分)</h4>

        <div class="ui list">
          <div class="ui small right labeled input">
            <label class="ui label">手順①</label>
            <%= f.number_field 'process1', data: {'input': true}, value: 20, readonly: true %>
            <div class="ui basic label">分</div>
          </div>
          <div class="item">
            <div class="ui labeled slider" data-slider="true" id="mandarat_slider_process1"></div>
          </div>
        </div>
        <div class="ui checkbox item">
          <%= f.check_box 'is_unlimited' %><label>無制限モード</label>
        </div>
        <div class="item">※ 無制限モードでは設定した時間による強制的なプロセスの進行が行われないため、時間を気にせずアイデア発想を行うことができます。</div>

        <h4 class="header-text  timer-setting">テーマ設定</h4>
        <div class="ui list">
          <div class="ui input item"><%= f.text_field 'theme', placeholder: "発想のテーマを入力してください", size: 50 %></div>
        </div>
        <h4 class="header-text">参加者(※招待する場合、開始後に右側に表示される招待ボタンをクリックしてURLをコピーし、他の参加者に伝えてください。)</h4>
        <div class="participant">
          <ul>
            <li>
              <i class="user circle icon"></i><%= current_user.user_name.blank? ? "Anonymous" : current_user.user_name %>
              (自分)
            </li>
          </ul>
        </div>
        <div class="ui center aligned grid">
          <div class="start-button">
            <%= f.submit 'はじめる', class: 'ui black button', id: 'start_button', disabled: true %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>