04.source/ideash/config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                  root GET    /                                                                                        top#index
#                          release_note GET    /release_note(.:format)                                                                  top#release_note
#                        account_signin GET    /account/signin(.:format)                                                                users/sessions#new
#                                       POST   /account/signin(.:format)                                                                users/sessions#create
#                        account_signup GET    /account/signup(.:format)                                                                users/registrations#new
#                                       POST   /account/signup(.:format)                                                                users/registrations#create
#                       account_signout GET    /account/signout(.:format)                                                               users/sessions#destroy
#                  account_profile_edit GET    /account/profile_edit(.:format)                                                          account#profile_edit
#                     user_confirmation GET    /user/confirmation(.:format)                                                             users/confirmations#show
#                                       POST   /user/confirmation(.:format)                                                             users/confirmations#create
#                          profile_edit GET    /account/edit(.:format)                                                                  users/registrations#profile_edit
#                        profile_update PATCH  /profile_update(.:format)                                                                users/registrations#profile_update
#                                  idea GET    /idea(.:format)                                                                          ideas#home
#                             idea_home GET    /idea/home(.:format)                                                                     ideas#home
#                          idea_history GET    /idea/history(.:format)                                                                  ideas#history
#                         idea_category GET    /idea/category(.:format)                                                                 ideas#category
#                         idea_memo_new GET    /idea/memo/new(.:format)                                                                 memo#new
#                                       POST   /idea/memo/new(.:format)                                                                 memo#new
#                             idea_memo POST   /idea/memo(.:format)                                                                     memo#create
#                                       GET    /idea/memo/edit/:id(.:format)                                                            memo#edit
#                                       PATCH  /idea/memo(.:format)                                                                     memo#update
#                idea_brainstorming_new GET    /idea/brainstorming/new(.:format)                                                        brainstorming#new
#             idea_brainstorming_replay GET    /idea/brainstorming/replay(.:format)                                                     brainstorming#replay
#             idea_brainstorming_create POST   /idea/brainstorming/create(.:format)                                                     brainstorming#create
#               idea_brainstorming_edit GET    /idea/brainstorming/edit/:id(.:format)                                                   brainstorming#edit
#                     jquery_test_index GET    /jquery_test/index(.:format)                                                             jquery_test#index
#                              ideachat GET    /ideachat(.:format)                                                                      ideachat#index
#                         ideachat_show GET    /ideachat/:id(.:format)                                                                  ideachat#show
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # INFO: トップページ
  root 'top#index'
  get 'release_note' => 'top#release_note', as: 'release_note'
  get 'top_category' => 'top#top_category', as: 'top_category'


  # INFO: devise(ユーザ認証関連)
  devise_for :users, skip: :all
  # devise_for :users
  devise_scope :user do
    get 'account/signin' => 'users/sessions#new'
    post 'account/signin' => 'users/sessions#create'
    get 'account/signup' => 'users/registrations#new'
    post 'account/signup' => 'users/registrations#create'
    get 'account/signout' => 'users/sessions#destroy'
    get 'account/profile_edit' => 'users/edit'
    # get 'user/confirmation/new' => 'users/confirmations#new'
    get 'user/confirmation' => 'users/confirmations#show'
    post 'user/confirmation' => 'users/confirmations#create'
    # INFO: アカウント設定
    # get 'account/edit' => 'users/registrations#edit'
    get 'account/edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'account/edit', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  # INFO: ユーザのホーム画面
  get 'idea/home' => 'ideas#home'
  get 'idea/history' => 'ideas#history'
  get 'idea/category' => 'ideas#category'
  # get 'idea/account' => 'ideas#account'

  # INFO: メモ
  get 'idea/memo/new' => 'memo#new'
  post 'idea/memo/new' => 'memo#new'
  post 'idea/memo' => 'memo#create'
  # get 'idea/memo/show' => 'memo#show'
  get 'idea/memo/edit/:id' => 'memo#edit'
  patch '/idea/memo' => 'memo#update'

  # INFO: ブレインストーミング
  get 'idea/brainstorming/new' => 'brainstorming#new'
  get 'idea/brainstorming/replay' => 'brainstorming#replay'
  post 'idea/brainstorming/create' => 'brainstorming#create'
  get 'idea/brainstorming/edit/:id' => 'brainstorming#edit', as: :idea_brainstorming_edit

  # INFO: マンダラート
  get'idea/mandarat/new' => 'mandarat#new'

04.source/ideash/app/models/idea.rb
# == Schema Information
#
# Table name: ideas
#
#  id               :string           not null, primary key
#  idea_category_id :integer
#  idea_name        :string
#  idea_description :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  option           :json
#  hash_link        :string
#
class Idea < ApplicationRecord
  before_create :set_id

  has_many :idea_logs
  has_many :user_idea
  has_many :user, through: :user_idea

  private

  def set_id
    # idが未設定 or 既に設定されている
    while self.id.blank? || User.find_by(id: self.id).present? do
      # 乱数20桁を設定
      self.id = SecureRandom.alphanumeric(20)
    end
  end

end

04.source/ideash/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  layout 'head_left_layout'
  require 'csv'

  def read_release_note_csv
    CSV.read("app/assets/csv/release_note.csv", headers: true, return_headers: false)
  end

  def home
    @release_note = read_release_note_csv
  end

  def history
    @user = User.find_by(id: current_user.id)
    @categories = IdeaCategory.all.index_by(&:id)
  end

  def category
  end

end

04.source/ideash/app/helpers/ideas_helper.rb
module IdeasHelper
end

04.source/ideash/app/views/ideas/account.html.erb
<input type=hidden id="is_updated" value=<%= @is_updated %>>

<%= form_for current_user, url: {action: 'profile_update'} do |f| %>
    <div class="ui raised segment">
      <div class="account_name">アカウント設定</div>
      <div class="account_setting">
        <table class="ui very basic table">
          <tbody>
          <tr>
            <td><%= f.label :user_name %></td>
            <td>
              <div class="ui input">
                <%= f.text_field :user_name,id:"account_input" %>
              </div>
            </td>
            <td>
              <div class="actions">
                <%= f.submit "Update", class: "ui teal button" %>
              </div>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  <div class="ui raised segment">
    <div class="account_name">サインアウト</div>
    <br>
    <div class="actions">
      <%= link_to "SignOut", account_signout_path, class: "ui inverted secondary button" %>
    </div>
  </div>
<% end %>

04.source/ideash/app/views/ideas/category.html.erb
<div class="category_segment">
  <h1 class="header">Create New</h1>
  <ul class="horizontal-list categories">
    <%= link_to idea_memo_new_path do %>
      <li class="horizontal-item category">
        <div class="techname_eng">Memo</div>
        <div class="techname_ja">メモ</div>
        <div><i class="edit huge icon techname_icon"></i></div>
        <div class="recommend_num">
          推奨人数：１人
        </div>
        <br>
        <i class="question circle outline icon js-modal-open" id="memo-more-info"></i>もっと詳しく
        <div class="explain">
          考えていることを書き連ねる<br>ことで、考えを整理し発想を<br>しやすくする技法
        </div>
        <hr>
        <div class="recommend_point">
          真っ白なフィールドを思考で<br>埋めていくことで新しい発想<br>が可能
        </div>
      </li>
    <% end %>
    <%= link_to idea_brainstorming_new_path do %>
      <li class="horizontal-item category">
        <div class="techname_eng">Brainstorming</div>
        <div class="techname_ja">ブレインストーミング</div>
        <div><i class="tags huge icon techname_icon"></i></div>
        <div class="recommend_num">
          推奨人数：２人〜
        </div>
        <br>
        <i class="question circle outline icon js-modal-open" id="brainstorming-more-info"></i>もっと詳しく
        <div class="explain">
          集団でアイデアを出し合うこ<br>とによって相互交錯の連鎖反<br>応や発想の誘発を期待する技法
        </div>
        <hr>
        <div class="recommend_point">
          アイデアを出し合い、融合さ<br>せることで、斬新で質な発想<br>が可能<br>
        </div>
      </li>
    <% end %>
    <%= link_to idea_mandarat_new_path do %>
      <li class="horizontal-item category">
        <div class="techname_eng">Mandarat</div>
        <div class="techname_ja">マンダラート</div>
        <div><i class="expand arrows alternate huge icon techname_icon"></i></div>
        <div class="recommend_num">
          推奨人数：１人〜
        </div>
        <br>
        <i class="question circle outline icon js-modal-open" id="mandarat-more-info"></i>もっと詳しく
        <div class="explain">
          ９×９のマス目に連想される<br>語句、または関連語句を記述<br>しアイデアのタネを育てる技法
        </div>
        <hr>
        <div class="recommend_point">
          アイデアの整理や拡大が図れ<br>効果的なアイデアを発掘する<br>ことが可能
        </div>
      </li>
    <% end %>
    <%= link_to idea_word_gacha_edit_path do %>
      <li class="horizontal-item category">
        <div class="techname_eng">Word GACHA</div>
        <div class="techname_ja">単語ガチャ</div>
        <div><i class="chart pie huge icon techname_icon"></i></div>
        <div class="recommend_num">
          推奨人数：１人
        </div>
        <br>
        <i class="question circle outline icon js-modal-open" id="word-gacha-more-info"></i>もっと詳しく
        <div class="explain">
          約750個の単語が出てくる<br>10連ガチャ<br>語彙ランクでレアリティが変化
        </div>
        <hr>
        <div class="recommend_point">
          ランダムに表示される単語か<br>ら発送の手助けに<br><br>
        </div>
      </li>
    <% end %>
    <%= link_to idea_word_slot_edit_path do %>
      <li class="horizontal-item category">
        <div class="techname_eng">Word SLOT</div>
        <div class="techname_ja">単語スロット</div>
        <div><i class="chess king huge icon techname_icon"></i></div>
        <div class="recommend_num">
          推奨人数：１人
        </div>
        <br>
        <i class="question circle outline icon js-modal-open" id="word-slot-more-info"></i>もっと詳しく
        <div class="explain">
          <br>約750個の単語が出てくる<br>スロット<br>
        </div>
        <hr>
        <div class="recommend_point">
          単語の組み合わせから自由な<br>発想へ繋がる<br><br>
        </div>
      </li>
    <% end %>
    <li class="horizontal-item category">
      <div class="techname_eng">Developing</div>
      <div class="techname_ja">開発中</div>
      <div><i class="moon huge icon techname_icon"></i></div>
      <div class="recommend_num">
        推奨人数：？人〜？人
      </div>
      <br>
      <i class="question circle outline icon js-modal-open" id="more-info"></i>もっと詳しく
      <div class="explain">
        現在<br>誠意<br>開発中です
      </div>
      <hr>
      <div class="recommend_point">
        楽しみに<br>お待ち<br>ください
      </div>
    </li>
  </ul>
  <div class="modal js-modal" id="memo-modal-window">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <%= image_tag 'memo_info_img', class: 'image_info_memo' %>
      <ul>
        <li class="info-text">①メモのタイトルを入力してください。</li>
        <li class="info-text">②メモの内容を入力してください。</li>
        <li class="info-text">③入力が終わったら「保存」ボタンをクリック！</li>
        <li class="info-text">保存されたメモは、右のリストから<br>確認・編集することができます。</li>
      </ul>
      <a class="js-modal-close" href="">閉じる</a>
    </div>
  </div>
  <div class="modal js-modal" id="brainstorming-modal-window">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <%= image_tag 'brainstorming_info_img1', class: 'image1_info_brainstorming' %>
      <%= image_tag 'brainstorming_info_img2', class: 'image2_info_brainstorming' %>
      <ul>
        <li class="info-text">①作成時に入力したテーマが表示されます。</li>
        <li class="info-text">②思いついた案を入力してEnterで送信。</li>
        <li class="info-text">③全ての参加者の案が表示されます。</li>
        <li class="info-text">④残り時間・参加者の確認やチャットが行えます。</li>
        <li class="info-text">⑤グループを追加することができます。</li>
        <li class="info-text">⑥グループ名を変更することができます。</li>
        <li class="info-text">⑦ドラッグ&ドロップで案をグルーピングできます。</li>
      </ul>
      <a class="js-modal-close" href="">閉じる</a>
    </div>
  </div>
  <div class="modal js-modal" id="mandarat-modal-window">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <%= image_tag 'mandarat_info_img1', class: 'image1_info_mandarat' %>
      <%= image_tag 'mandarat_info_img2', class: 'image2_info_mandarat' %>
      <ul>
        <li class="info-text">①メイン・サブテーマが表示されます。</li>
        <li class="info-text">②入力してマスを埋めていきます。<br>他の参加者が編集していると色が変わります。</li>
        <li class="info-text">③矢印の方向に移動します。上下左も同様。</li>
        <li class="info-text">④全体画面（画像２枚目）を見ることができます。</li>
        <li class="info-text">⑤現在開いている場所が表示されます。<br>選択することで移動することもできます。</li>
        <li class="info-text">⑥メインテーマとサブテーマが表示されます。</li>
        <li class="info-text">⑦残り時間・参加者の確認やチャットが行えます。</li>
        <li class="info-text">⑧81マス全てが表示されます。（閲覧のみ）<br>画面をクリックすることで元の画面に戻れます。</li>
      </ul>
      <a class="js-modal-close" href="">閉じる</a>
    </div>
  </div>
  <div class="modal js-modal" id="word-gacha-model-window">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <%= image_tag 'gacha_info_img1', class: 'image1_info_gacha' %>
      <%= image_tag 'gacha_info_img2', class: 'image2_info_gacha' %>
      <ul>
        <li class="info-text">①「回す」を押すと結果画面（画像右）に移動します。</li>
        <li class="info-text">②初期画面（画像左）に移動します。</li>
        <li class="info-text">③ランダムに選ばれた10個のワードが表示されます。</li>
      </ul>
      <a class="js-modal-close" href="">閉じる</a>
    </div>
  </div>
  <div class="modal js-modal" id="word-slot-model-window">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <%= image_tag 'slot_info_img', class: 'image_info_slot' %>
      <ul>
        <li class="info-text">①「回す」を押すとスロットが始まります。</li>
        <li class="info-text">②スロットを止めることができます。</li>
        <li class="info-text">③ランダムに選ばれたワードが表示されます。</li>
      </ul>
      <a class="js-modal-close" href="">閉じる</a>
    </div>
  </div>
</div>

04.source/ideash/app/views/ideas/history.html.erb
<%# TODO: サムネイル表示に対応する %>
<div class="ui container">
  <table class="ui selectable celled striped table">
    <thead>
    <tr>
      <th colspan="3">
        Recent Creation
      </th>
    </tr>
    </thead>
    <tbody>
    <% @user.idea.reverse.each do |idea| %>
      <% if Rails.env.test? %>
        <tr class="feature-test-history">
      <% else %>
        <tr onclick="location.href='<%= "#{@categories[idea.idea_category_id]['manage_name']}/edit/#{idea.id}" %>'">
      <% end %>
      <td class='collapsing'>
        <i class="folder icon"></i>
        <%= "#{@categories[idea.idea_category_id]["idea_category_name"]}" %>
      </td>
      <td>
        <%= idea.idea_name.truncate(20, omission: '...') %>
      </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

04.source/ideash/app/views/ideas/home.html.erb
<div class="home_center">
  <div class="ideash_explain">
    <div class="home_image">
      <%= image_tag 'thinkman.webp', class: 'image_home_think_man' %>
    </div>
    <div class="home_text">
      <p>
        Inspiration<br>
        with<br>
        Ideash<br>
      </p>
    </div>
  </div>
  <div class="step_content">
    <h5>how to use</h5>
    <div class="ui steps">
      <div class="step">
        <i class="gem icon"></i>
        <div class="content">
          <div class="title">Choose</div>
          <div class="description">発想手法を選ぶ</div>
        </div>
      </div>
      <div class="step">
        <i class="handshake icon"></i>
        <div class="content">
          <div class="title">Get together</div>
          <div class="description">参加者を集める</div>
        </div>
      </div>
      <div class="step">
        <i class="gem icon"></i>
        <div class="content">
          <div class="title">Follow us</div>
          <div class="description">Ideashに従う</div>
        </div>
      </div>
      <div class="step">
        <i class="lightbulb outline teal icon"></i>
        <div class="content">
          <div class="title">Inspiration !</div>
          <div class="description">アイデアを思いつく</div>
        </div>
      </div>
    </div>
  </div>
  <% if Rails.env.development? %>
    <div class="advertisement">
      <div class="ui large leaderboard test ad" data-text="Large Leaderboard">*develop modeでのみ表示</div>
      <div class="ui large leaderboard test ad" data-text="Large Leaderboard">*develop modeでのみ表示</div>
    </div>
  <% end %>
</div>
<div class="home_right">
  <div class="release_info">
    <div class="ui tiny list">
      <% @release_note.reverse_each do |row| %>
        <div class="item">
          <i class="angle right icon"></i>
          <div class="release_note_content">
            <%= link_to row['description'].split("//")[0], release_note_path, class: 'header' %>
            <div class="description"><%= row['date'] %></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="twitter_window">
    <a class="twitter-timeline" data-chrome="noheader nofooter noborders" data-width="100%" data-height="100%" data-border-color="#2E2F30" href="https://twitter.com/Ideash_5k?ref_src=twsrc%5Etfw"></a>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
  <div class="about_us">
    <div class="about_us_content">
      Ideashは5Kという専門学生5名のチームによって開発されています。
      ご意見等はTwitterまたはGithubにお願いいたします。
      <div class="link_icons">
        <a href="https://github.com/ASO1901029/sk2020_5K"><i class="github link purple big icon"></i>Github</a>　　
        <a href="https://twitter.com/Ideash_5k"><i class="twitter link blue big icon"></i>Twitter</a>
      </div>
    </div>
  </div>
</div>