04.source/ideash/config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                  root GET    /                                                                                        top#index
#                          release_note GET    /release_note(.:format)                                                                  top#release_note
#                        account_signin GET    /account/signin(.:format)                                                                users/sessions#new
#                                       POST   /account/signin(.:format)                                                                users/sessions#create
#                        account_signup GET    /account/signup(.:format)                                                                users/registrations#new
#                                       POST   /account/signup(.:format)                                                                users/registrations#create
#                       account_signout GET    /account/signout(.:format)                                                               users/sessions#destroy
#                  account_profile_edit GET    /account/profile_edit(.:format)                                                          account#profile_edit
#                     user_confirmation GET    /user/confirmation(.:format)                                                             users/confirmations#show
#                                       POST   /user/confirmation(.:format)                                                             users/confirmations#create
#                          profile_edit GET    /account/edit(.:format)                                                                  users/registrations#profile_edit
#                        profile_update PATCH  /profile_update(.:format)                                                                users/registrations#profile_update
#                                  idea GET    /idea(.:format)                                                                          ideas#home
#                             idea_home GET    /idea/home(.:format)                                                                     ideas#home
#                          idea_history GET    /idea/history(.:format)                                                                  ideas#history
#                         idea_category GET    /idea/category(.:format)                                                                 ideas#category
#                         idea_memo_new GET    /idea/memo/new(.:format)                                                                 memo#new
#                                       POST   /idea/memo/new(.:format)                                                                 memo#new
#                             idea_memo POST   /idea/memo(.:format)                                                                     memo#create
#                                       GET    /idea/memo/edit/:id(.:format)                                                            memo#edit
#                                       PATCH  /idea/memo(.:format)                                                                     memo#update
#                idea_brainstorming_new GET    /idea/brainstorming/new(.:format)                                                        brainstorming#new
#             idea_brainstorming_replay GET    /idea/brainstorming/replay(.:format)                                                     brainstorming#replay
#             idea_brainstorming_create POST   /idea/brainstorming/create(.:format)                                                     brainstorming#create
#               idea_brainstorming_edit GET    /idea/brainstorming/edit/:id(.:format)                                                   brainstorming#edit
#                     jquery_test_index GET    /jquery_test/index(.:format)                                                             jquery_test#index
#                              ideachat GET    /ideachat(.:format)                                                                      ideachat#index
#                         ideachat_show GET    /ideachat/:id(.:format)                                                                  ideachat#show
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # INFO: トップページ
  root 'top#index'
  get 'release_note' => 'top#release_note', as: 'release_note'
  get 'top_category' => 'top#top_category', as: 'top_category'


  # INFO: devise(ユーザ認証関連)
  devise_for :users, skip: :all
  # devise_for :users
  devise_scope :user do
    get 'account/signin' => 'users/sessions#new'
    post 'account/signin' => 'users/sessions#create'
    get 'account/signup' => 'users/registrations#new'
    post 'account/signup' => 'users/registrations#create'
    get 'account/signout' => 'users/sessions#destroy'
    get 'account/profile_edit' => 'users/edit'
    # get 'user/confirmation/new' => 'users/confirmations#new'
    get 'user/confirmation' => 'users/confirmations#show'
    post 'user/confirmation' => 'users/confirmations#create'
    # INFO: アカウント設定
    # get 'account/edit' => 'users/registrations#edit'
    get 'account/edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'account/edit', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  # INFO: ユーザのホーム画面
  get 'idea/home' => 'ideas#home'
  get 'idea/history' => 'ideas#history'
  get 'idea/category' => 'ideas#category'
  # get 'idea/account' => 'ideas#account'

  # INFO: メモ
  get 'idea/memo/new' => 'memo#new'
  post 'idea/memo/new' => 'memo#new'
  post 'idea/memo' => 'memo#create'
  # get 'idea/memo/show' => 'memo#show'
  get 'idea/memo/edit/:id' => 'memo#edit'
  patch '/idea/memo' => 'memo#update'

  # INFO: ブレインストーミング
  get 'idea/brainstorming/new' => 'brainstorming#new'
  get 'idea/brainstorming/replay' => 'brainstorming#replay'
  post 'idea/brainstorming/create' => 'brainstorming#create'
  get 'idea/brainstorming/edit/:id' => 'brainstorming#edit', as: :idea_brainstorming_edit

  # INFO: マンダラート
  get'idea/mandarat/new' => 'mandarat#new'

04.source/ideash/app/views/shared/_debug_menu.html.erb
<!-- デバッグメニュー -->
<%# debug_menuをproduction環境で見せたくないためapplication.jsには書かない %>
<%= javascript_pack_tag 'shared/_debug_menu' %>
<div class="ui modal" id="debug-modal-window">
  <div class="ui segments">
    <div class="ui segment">
      <div class="ui header">デバッグメニュー</div>
    </div>
    <div class="ui segment">
      <div class="ui list">
        <div class="ui label">STATUS INFO</div>
        <% if user_signed_in? %>
          <div class="item">
            <i class="users icon"></i>
            USER-ID:<%= current_user.id %>
          </div>
          <div class="item">
            <i class="users icon"></i>
            USER-NAME:<%= current_user.user_name %>
          </div>
          <div class="item">
            <i class="mail icon"></i>
            EMAIL:<%= current_user.email %>
          </div>
        <% else %>
          未ログイン
        <% end %>
      </div>
    </div>
    <div class="ui segment">
      <div class="ui list">
        <div class="ui label">RAILS INFO</div>
        <div class="item">
          <i class="terminal icon"></i>
          CONTROLLER: <%= controller_name %>
        </div>
        <div class="item">
          <i class="code icon"></i>
          ACTION: <%= action_name %>
        </div>
      </div>
    </div>
    <div class="ui segment">
      <div class="ui actions">
        <% if user_signed_in? %>
          <%= link_to "サインアウト", account_signout_path, class: 'ui red button' %>
        <% else %>
          <%= link_to "サインイン", account_signin_path, class: 'ui blue button' %>
          <%= link_to "サインアップ", account_signup_path, class: 'ui green button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

04.source/ideash/app/views/shared/_editmenu.html.erb
<%= javascript_pack_tag 'shared/_editmenu' %>
<input type="hidden" id="user_id" value="<%= current_user.id %>">
<!-- 1 -->
<div class="ui right fixed vertical menu block-edit-sidebar" id="edit_menu">
  <!-- 2 -->
  <div class="item timer">
    <%# TODO: タイマー実装後に削除 %>
    <!-- 時計 -->
    <small>現在時刻</small><br>
    <div id="RealtimeClockArea2" class="timer_min"></div>
  </div>
  <% if controller_name == 'brainstorming' then %>
    <%# ブレインストーミング %>
    <div class="item explain">
      <div class="header-text">
        <i class="question circle outline icon"></i>ブレインストーミング
      </div>
      <ul class="explain-list">
        <li class="bold">アイデア出し： 無制限</li>
        <li><s>意見だし　　：</s></li>
        <li><s>グルーピング：</s></li>
      </ul>
    </div>
  <% elsif controller_name == 'mandarat' %>
    <%# マンダラート %>
    <div class="item explain">
      <div class="header-text">
        <i class="question circle outline icon"></i>マンダラート
      </div>
      <ul class="explain-list">
        <li class="bold">アイデア出し： 無制限</li>
      </ul>
    </div>
  <% end %>
  <!-- 4 -->
  <div class="item participant">
    <div class="header-text">
      参加者
    </div>
    <div class="member">
      <ul class="users">
        <% for user in users %>
          <li id="participant_<%= user.id %>">
            <i class="user circle icon"></i><%= user.user_name.blank? ? "Anonymous" : user.user_name %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <button class="ui small button" id="copy_invite_link" value="<%= request.url %>">
    招待<i class="clipboard outline icon"></i>
  </button>

  <button class="ui small button" id="reset_chat_position">
    チャットの位置リセット
  </button>

  <div class="item chat">
    <div class="header-text" title="ドラッグして移動">
      chat
      <%= image_tag "draggable.svg", id: "draggable_svg" %>
    </div>
    <div class="ui input mini chat-input">
      <%= text_field_tag 'idea_chat', nil, placeholder: '話しかける...', data: {behavior: 'idea_speaker'} %>
    </div>
    <div class="chat-area">
      <div class="inline field">
        <div class="chat_contents">
          <% preview_user_id = nil %>
          <% for idea_log in @idea_logs.reverse %>
            <% if idea_log.query['mode'] == 'chat' %>
              <% if preview_user_id != idea_log.query['user_id'] %>
                </div>
                <div class="chat_content" name="chatuser_<%= idea_log.query['user_id'] %>">
                  <h6 class="chat_username"><%= idea_log.query['chat']['user_name'] %></h6>
              <% end %>
              <% if current_user.id == idea_log.query['user_id'] %>
                <div class="ui right pointing label chat_message"><%= idea_log.query['chat']['content'] %></div>
              <% else %>
                <div class="ui left pointing label chat_message"><%= idea_log.query['chat']['content'] %></div>
              <% end %>
              <% preview_user_id = idea_log.query['user_id'] %>
            <% end %>
          <% end %>
          </div>
          </div>
    </div>
  </div>
</div>

04.source/ideash/app/views/shared/_header.html.erb
<div class="ui menu">
    <%= image_tag 'icon.svg', class: "icon_image" %>
</div>

04.source/ideash/app/views/shared/_left_menu.html.erb
<%# 左サイドバー %>
<div class="ui vertical menu left_menu" id="left_menu">
  <a class="item" id="left_menu_hide_button">
    <i class="angle double left grey icon"></i>　
  </a>
  <%= link_to "ホーム", idea_home_path, class: "item" %>
  <%= link_to "新規作成", idea_category_path, class: "item" %>
  <div class="menu">
    <%= link_to "ブレインストーミング", idea_brainstorming_new_path, class: "item" %>
    <%= link_to "マンダラート", idea_mandarat_new_path, class: "item" %>
    <%= link_to "単語ガチャ", idea_word_gacha_edit_path, class: "item" %>
    <%= link_to "単語スロット", idea_word_slot_edit_path, class: "item" %>
    <%= link_to "メモ", idea_memo_new_path, class: "item" %>
  </div>
  <%= link_to "履歴", idea_history_path, class: "item" %>
  <%= link_to "アカウント", profile_edit_path, class: "item" %>
</div>

<div class="ui vertical icon menu left_menu" id="left_icon_menu">
  <a class="popup item" id="left_menu_show_button" data-content="メニューを開く" data-position="right center">
    <i class="angle double right grey icon"></i>
  </a>
  <a class="popup item" href="<%= idea_home_path %>" data-content="ホーム" data-position="right center">
    <i class="home grey icon"></i>
  </a>
  <a class="popup item" href="<%= idea_category_path %>" data-content="新規作成" data-position="right center">
    <i class="edit grey icon"></i>
  </a>

  <a class="popup item" href="<%= idea_history_path %>" data-content="履歴" data-position="right center">
    <i class="folder open grey icon"></i>
  </a>
  <a class="popup item" href="<%= profile_edit_path %>" data-content="設定" data-position="right center">
    <i class="cog grey icon"></i>
  </a>
</div>

04.source/ideash/app/views/shared/_memomenu.html.erb
<%= link_to "/idea/memo/edit/#{memo.id}" do %>
  <% if memo.idea_category_id == 1 %>
    <div class="item memos">
      <div class="ui header details">
        <div class="content memo-text">
          <%= memo.idea_name %>
          <div class="sub header memo-date">
            <%= memo.updated_at %>
          </div>
        </div>
        <i class="universal access icon memo-icon"></i>
      </div>
      <div class="memo-sample">
        <%= memo.idea_description %>
      </div>
    </div>
    <div class="ui divider"></div>
  <% end %>
<% end %>

04.source/ideash/app/views/shared/_right_menu.html.erb
<input type="hidden" id="user_id" value="<%= current_user.id %>">
<!-- 1 -->
<div class="ui right fixed vertical menu block-edit-sidebar right_menu" id="right_menu">
  <a class="item" id="right_menu_hide_button">
    <i class="angle double right grey icon"></i>　
  </a>

  <!-- 2 -->
  <div class="item timer">
    <%# TODO: タイマー実装後に削除 %>
    <!-- 時計 -->
    <small id="time_title"></small><br>
    <div id="remaining"></div>
  </div>
  <% if controller_name == 'brainstorming' then %>
    <%# ブレインストーミング %>
    <div class="item explain">
      <div class="header-text">
        <i class="question circle outline icon js-modal-open"></i>ブレインストーミング
      </div>
      <ul class="explain-list">
        <li class="bold"><div id="time0"></div></li>
        <li class="bold"><div id="time1"></div></li>
        <li class="bold"><div id="time2"></div></li>
      </ul>
    </div>
  <% elsif controller_name == 'mandarat' %>
    <%# マンダラート %>
    <div class="item explain">
      <div class="header-text">
        <i class="question circle outline icon js-modal-open"></i>マンダラート
      </div>
      <ul class="explain-list">
        <li class="bold"><div id="time0"></div></li>
      </ul>
    </div>
  <% end %>
  <!-- 4 -->
  <div class="item participant">
    <div class="header-text">
      参加者
    </div>
    <div class="member">
      <ul class="users">
        <% for user in users %>
          <li id="participant_<%= user.id %>">
            <i class="user circle icon"></i><%= user.user_name.blank? ? "Anonymous" : user.user_name %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <button class="ui small button" id="copy_invite_link" value="<%= request.url %>">
    招待<i class="clipboard outline icon"></i>
  </button>

  <button class="ui small button" id="reset_chat_position">
    チャットの位置リセット
  </button>
</div>

<div class="ui vertical icon menu right_menu" id="right_icon_menu">
  <a class="popup item" id="right_menu_show_button" data-content="メニューを開く" data-position="right center">
    <i class="angle double left grey icon"></i>
  </a>
</div>

<%# チャット欄 %>
<div class="chat">
  <div class="header-text" title="ドラッグして移動">
    chat
    <%= image_tag "draggable.svg", id: "draggable_svg" %>
  </div>
  <div class="ui input mini chat-input">
    <%= text_field_tag 'idea_chat', nil, placeholder: '話しかける...', data: {behavior: 'idea_speaker'} %>
  </div>
  <div class="chat-area">
    <div class="inline field chat_contents">
      <% preview_user_id = nil %>
      <% for idea_log in @idea_logs.reverse %>
        <% if idea_log.query['mode'] == 'chat' %>
          <% if preview_user_id != idea_log.query['user_id'] %>
            <div class="chat_content" name="chatuser_<%= idea_log.query['user_id'] %>">
              <h6 class="chat_username"><%= idea_log.query['chat']['user_name'] %></h6>
          <% end %>
          <% if current_user.id == idea_log.query['user_id'] %>
            <div class="ui right pointing label chat_message"><%= idea_log.query['chat']['content'] %></div>
          <% else %>
            <div class="ui left pointing label chat_message"><%= idea_log.query['chat']['content'] %></div>
          <% end %>
          <% preview_user_id = idea_log.query['user_id'] %>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>